### ISSUE TITLE
`APIObject` Secret Storage

### ISSUE THREAD

**Issue by nh758** [digi-serve/ab_service_appbuilder#58]
## Requirements

1.  Builder can add a secret/mark a header value as secret
2.  Don't store secrets in definitions
3.  Encrypt and store in new DB Table?
4.  Add secrets when making requests

### Tasks
- [ ] Write Documentation

## Reference

**Comment by wongpratan** [comment]
Thank you @zachhh3 

![secret key](https://github.com/digi-serve/ab_service_appbuilder/assets/545045/8c962bf4-5cad-421d-80fc-27d3f4fb9f7e)

https://medium.com/@moghiny/diffie-hellman-key-exchange-theory-and-practice-with-node-js-ab2575e14e8
https://www.educative.io/answers/what-is-node-cryptodiffiehellmanoptions
